=== haoxiangmei315-CHN/AF-Individual-UD05.1.-XSD-RegEx/usuarios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombreUsuario" type="tipoNombreUsuario"/>
                            <xs:element name="email" type="tipoEmail"/>
                            <xs:element name="telefono" type="tipoTelefono"/>
                            <xs:element name="codigoPostal" type="tipoCodigoPostal"/>
                            <xs:element name="contrasena" type="tipoContrasena"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipoNombreUsuario">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z][a-zA-Z0-9]{2,14}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoEmail">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTelefono">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\+34)?[6-9][0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCodigoPostal">
        <xs:restriction base="xs:string">
            <xs:pattern value="(0[1-9]|[1-4][0-9]|5[0-2])[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoContrasena">
        <xs:restriction base="xs:string">
            <xs:minLength value="8"/>
            <xs:pattern value="[a-zA-Z0-9!@#\$%\^\&amp;\*\(\)_\+\-\=\{\}\[\]\|:;,.?]+"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== haoxiangmei315-CHN/AF-Individual-UD05.1.-XSD-RegEx/usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usuarios.xsd">
    
    <usuario>
        <nombreUsuario>carlosDev</nombreUsuario>
        <email>carlos.prueba@gmail.com</email>
        <telefono>+34600123456</telefono>
        <codigoPostal>41013</codigoPostal>
        <contrasena>Sevilla_2024!</contrasena>
    </usuario>

    <usuario>
        <nombreUsuario>laura99</nombreUsuario>
        <email>laura99@hotmail.com</email>
        <telefono>954987654</telefono>
        <codigoPostal>28001</codigoPostal>
        <contrasena>P4ssw0rd!</contrasena>
    </usuario>

    </usuarios>
